/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303031",
        "tertiary-container": "#454747",
        "secondary-fixed": "#e5e2e1",
        primary: "#680200",
        "surface-container": "#efeded",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-fixed-variant": "#8b1a0e",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#8b1a0e",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e2e2",
        "on-background": "#1b1c1c",
        error: "#ba1a1a",
        background: "#fbf9f8",
        "surface-dim": "#dbdad9",
        "primary-fixed": "#ffdad4",
        "inverse-primary": "#ffb4a7",
        "surface-container-high": "#e9e8e7",
        "outline-variant": "#e0bfba",
        tertiary: "#2f3131",
        "on-error": "#ffffff",
        "on-surface-variant": "#59413d",
        "primary-fixed-dim": "#ffb4a7",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#474746",
        "tertiary-fixed": "#e2e2e2",
        secondary: "#5f5e5e",
        outline: "#8c716c",
        "on-tertiary-fixed-variant": "#454747",
        "on-surface": "#1b1c1c",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-container": "#e2dfde",
        "on-secondary-container": "#636262",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f2f0f0",
        "on-primary-fixed": "#400100",
        "surface-tint": "#ac3323",
        "surface-variant": "#e4e2e2",
        surface: "#fbf9f8",
        "on-primary-container": "#ff9a8a",
        "surface-bright": "#fbf9f8",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#b4b5b5",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-low": "#f5f3f3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "8px",
        "sidebar-width": "232px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "card-gap": "24px",
      },
      fontFamily: {
        // Police par défaut de toute l'appli — sans elle, Tailwind retombe
        // sur la pile système générique pour tout texte qui n'a pas
        // explicitement une classe font-headline-*/font-body-*/font-label-*
        // (ex : les gros chiffres de KPI dans les pages "template").
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-xl": ["Manrope"],
        "label-md": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
